---
- name: Add an Access List
  hosts: ios


  tasks:

  - name: LOAD NEW ACL INTO DEVICE
    ios_config:
      authorize: yes
      lines:
        - 10 permit ip host 1.1.1.1 any log
        - 30 permit ip host 3.3.3.3 any log
        - 40 permit ip host 4.4.4.4 any log
      parents: ip access-list extended test
      before: no ip access-list extended test
